import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "./globals.css";


const josefinSans = Josefin_Sans({
variable: "--font--josefin-sans",
subsets: ["latin"]
});


//JosefinSans-Light, sans-serif

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefinSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
